services:
  - type: web
    name: cortex-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: USE_GROQ
        value: "True"
      - key: USE_GEMINI
        value: "False"
      - key: USE_AWS_BEDROCK
        value: "False"
      - key: GROQ_MODEL
        value: "llama-3.1-8b-instant"
      - key: GROQ_API_KEY
        sync: false
